site_name: bollywood_data_science
site_description: Refreshingly simple new project generation.
site_url: https://github.com/charmoniumQ/bollywood-data-science

theme:
    name: 'material'

repo_name: charmoniumQ/bollywood-data-science
repo_url: https://github.com/charmoniumQ/bollywood-data-science
edit_uri: ''

nav:
    - bollywood_data_science: 'index.md'
