queries:
  defaults: &defaults
  wikidata_get: &wikidata_get
    <<: *defaults
    query: |
      PREFIX wd: <http://www.wikidata.org/entity/>
      PREFIX wdt: <http://www.wikidata.org/prop/direct/>
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      CONSTRUCT {
        ?person rdf:subject ?person .
        ?person wdt:P106 ?occupation .
        ?person wdt:P345 ?personImdbId .
        ?person wdt:P21 ?sex . 
        ?person wdt:P19 ?placeOfBirth .
        ?person wdt:P22 ?father .
        ?person wdt:P25 ?mother .
        ?person wdt:P3448 ?stepParent .
        ?person wdt:P26 ?spouse .
        ?person wdt:P69 ?school .
        ?person wdt:P551 ?residence .
        ?person wdt:P172 ?ethnicGroup .
        ?person wdt:P149 ?religion .
        ?person wdt:1412 ?langauage .
        ?person wdt:P39 ?positionHeld .
      } WHERE {
        OPTIONAL { ?person wdt:P21 ?sex . } .
        OPTIONAL { ?person wdt:P345 ?personImdbId . } .
        OPTIONAL { ?person wdt:P19 ?placeOfBirth . } .
        OPTIONAL { ?person wdt:P22 ?father . } .
        OPTIONAL { ?person wdt:P25 ?mother . } .
        OPTIONAL { ?person wdt:P3448 ?stepParent . } .
        OPTIONAL { ?person wdt:P26 ?spouse . } .
        OPTIONAL { ?person wdt:P69 ?school . } .
        OPTIONAL { ?person wdt:P551 ?residence . } .
        OPTIONAL { ?person wdt:172 ?ethnicGroup . } .
        OPTIONAL { ?person wdt:149 ?religion . } .
        OPTIONAL { ?person wdt:1412 ?langauage . } .
        OPTIONAL { ?person wdt:P39 ?positionHeld . } .
      }

    # mother, father, stepParent, spouse, child, relative, sibling
  wikidata_post:
    <<: *wikidata_get
    method: POST
