from typing import Any

class Node:
    def toPython(self) -> Any: ...
    def __eq__(self, other: object) -> bool: ...
    def __neq__(self, other: object) -> bool: ...
    def __leq__(self, other: object) -> bool: ...
    def __geq__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...

class Identifier(Node, str): ...
class URIRef(Identifier): ...
class BNode(Identifier): ...
class Variable(Identifier): ...

class Literal(Identifier):
    def __init__(self, x: Any, datatype: Any = None) -> None: ...
