from typing import Any

class Node: ...
class Identifier(Node, str): ...
class URIRef(Identifier): ...
class BNode(Identifier): ...
class Variable(Identifier): ...
class Literal(Identifier):
    def __init__(self, x: Any, datatype: Any = None) -> None: ...
