name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
      fail-fast: true

    steps:

      - uses: actions/checkout@master

      - uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: ${{ matrix.python-version }}
          args: install

      - run: poetry run scripts/test.sh check

      - uses: codecov/codecov-action@v1
